package com.example.data

data class FaqItem(
    val question: String,
    val answer: String
)

object FaqData {
    val items = listOf(
        FaqItem(
            question = "What does Sky Prompt Designer do?",
            answer = "Sky Prompt Designer takes any simple idea or topic and automatically engineers a comprehensive, structured prompt. It synthesizes an authoritative AI role, clear objective, context, sequenced instructions, quality constraints, and precise output format to guarantee significantly higher quality responses from AI models."
        ),
        FaqItem(
            question = "Do I need to know prompt engineering?",
            answer = "Not at all! That is the exact problem Sky Prompt Designer solves. You only provide what you want to create (e.g. 'Build a fitness app strategy'), and Sky constructs the advanced persona framing, negative constraints, and structured directives on your behalf."
        ),
        FaqItem(
            question = "Can I use the generated prompts with ChatGPT?",
            answer = "Yes! Prompts generated by Sky Prompt Designer are universal and optimized for all top-tier foundation models, including ChatGPT (GPT-4o), Anthropic Claude 3.5, Google Gemini, and Microsoft Copilot."
        ),
        FaqItem(
            question = "Can Sky Prompt Designer improve my existing prompts?",
            answer = "Yes. In the 'Improve My Prompt' tab, paste any existing prompt. Sky will scan it for ambiguous language, missing context, and loose instructions, then output an improved version with enhanced specificity and structure."
        ),
        FaqItem(
            question = "What is included in Pro?",
            answer = "Pro includes unlimited prompt generation, prompt improvement, advanced parameter tuning (roles, audience, tone, length, constraints), full prompt history, export tools, quality scoring heuristics, and priority AI processing."
        ),
        FaqItem(
            question = "How much does Pro cost?",
            answer = "Pro is $10/month. You can start completely free to test the core prompt designer, and upgrade whenever you need unlimited generation or advanced controls. Cancel anytime."
        )
    )
}
